# Generated by Django 4.2.7 on 2023-12-14 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_text', models.CharField(max_length=300)),
                ('color', models.IntegerField(default=12695472)),
                ('week_num', models.IntegerField(default=0)),
                ('day_num', models.IntegerField(default=0)),
                ('number_in_day', models.IntegerField(default=0)),
                ('time', models.TimeField()),
                ('role_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WeekScheduler.role')),
            ],
        ),
    ]
