# Generated by Django 4.2.7 on 2023-12-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeekScheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
